### ISSUE TITLE
Description field

### ISSUE THREAD

**Issue by naitso** [znuny/Znuny4OTRS-ExternalURLJump#5] opened 2020-09-09 09:11 UTC
Hi, on version 6.0.4 the field Description by default is empty, but on edit is mandatory and does not accept white space. 
When filled, saved and deployed the voice "Jump to Znuny!" on menu bar disappear, so is impossible to customize this entry as written in the guide or github doc.

**Comment by dennykorsukewitz** [comment] 2020-09-09 09:13
Hi @naitso 
thanks for your report.
We will check it and give you feedback.

best greetings 😃

**Comment by dennykorsukewitz** [comment] 2020-09-09 10:42
Hi @naitso 

I assume that you are talking about this configuration:
Frontend::Navigation####ExternalURLJump###1

Can you please send me your configuration.
A screenshot would be enough for now.
Please make sure that all information are visible.

greetings.

**Comment by naitso** [comment] 2020-09-09 11:11
Hi @dennykorsukewitz 
the configuration i used is  Frontend::Navigation###ExternalURLJump###1Znuny4OTRS-ExternalURLJump.xml  

on mine only 3 ###, in your 4#
![image](https://user-images.githubusercontent.com/6575476/92590427-8184b780-f29c-11ea-9e44-36c0d11e0e29.png)

Default settings

![image](https://user-images.githubusercontent.com/6575476/92590584-c3adf900-f29c-11ea-84a2-47dd5c9391a5.png)

menu is visible:
![image](https://user-images.githubusercontent.com/6575476/92590617-cf99bb00-f29c-11ea-8398-11933c81eaab.png)


If i deploy the following settings the menu disappear
![image](https://user-images.githubusercontent.com/6575476/92590742-0079f000-f29d-11ea-8132-54e6ce296acd.png)

![image](https://user-images.githubusercontent.com/6575476/92590947-577fc500-f29d-11ea-984e-323ace7735ce.png)

OTRS Community version
![image](https://user-images.githubusercontent.com/6575476/92591283-e8ef3700-f29d-11ea-865d-3d9e64c11106.png)

thanks

**Comment by dennykorsukewitz** [comment] 2020-09-10 08:51
Hi @naitso 
thanks for your feedback.
You're right it's only 3 #.

I cleaned the code and added a standard description.

So far I could not find any errors.
The changes in the description do not cause any errors either.

Can you uninstall the package and install the new version 6.0.5, please.

**Comment by naitso** [comment] 2020-09-10 10:17
Hi @dennykorsukewitz 
version 6.0.5 installed 
![image](https://user-images.githubusercontent.com/6575476/92716518-354e7b80-f35f-11ea-96c6-2dc7be673899.png)
but nothing changed
for example, when change URL to google.com 
![image](https://user-images.githubusercontent.com/6575476/92716772-8c545080-f35f-11ea-855e-8542f260ec24.png)
and deploy the menu disappear

**Comment by dennykorsukewitz** [comment] 2020-09-14 15:45
Hi @naitso 

currently i simply cannot reproduce the problem.
Which other packages do you have installed?
Do you have any error messages (SystemLog)?
Can you save other SysConfigs without getting problems?

**Comment by naitso** [comment] 2020-09-17 12:35
Hi @dennykorsukewitz 
Apologize for the late reply, this is the packages installed in my system
![image](https://user-images.githubusercontent.com/6575476/93470985-0736e180-f8f3-11ea-9084-a9f160fd00d5.png)

No errors in system log and no other problems for other configs  until today

**Comment by dennykorsukewitz** [comment] 2020-10-27 11:54
Hi @naitso,
sorry for the late message.
We can not reproduce it.

Can you please check the following:

1. reset all settings of this package to "factory" default. Does it work now?

2. if not, please change the following in the SysConfig (**Frontend::Navigation###ExternalURLJump###1**)
	- remove **AccessKey**
	- change **Prio** to **10001**

Do you have your own xml configurations (custom)?

best greetings 😃

**Comment by dennykorsukewitz** [comment] 2020-11-03 09:18
Hi @naitso,
we have tried to reproduce it again.
But we simply do not succeed. :/ 
Somewhere in your settings it must be something different than normal.

I will close the issue now, if you find something and we can support you, let me know.

best regards 🚀

**Closed by dennykorsukewitz** 2020-11-03 09:18 UTC
Labels: bug

**Comment by naitso** [comment] 2021-01-08 07:46
Hi dennykorsukewitz,
just an update, i think the problem was related to the old version of OTRS, i started from 6.0.5 and update over and over till 6.0.26.
The past week i started from a fresh installation of 6.0.30 and restored only database, now ExternalURL works.
Thank you very much
Regards naitso

**Comment by dennykorsukewitz** [comment] 2021-01-08 08:18
Hi @naitso,
good to hear from you and great that you could solve the problem now.

Thanks for giving us feedback on the issue again.

Maybe you have already heard about the current situation for the **"((OTRS)) Community Edition".**
Have a look at this then:
https://www.znuny.org/why

best regards 🚀
